# Automatically generated by: ros2nix
{ lib, buildRosPackage, ament-cmake, ament-lint-auto, ament-lint-common
, camera-info-manager, cv-bridge, image-geometry, image-transport, rclcpp
, rclcpp-components, sensor-msgs, std-msgs, vision-opencv }:
buildRosPackage rec {
  pname = "ros-rolling-cpp-pubsub";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [
    camera-info-manager
    cv-bridge
    image-geometry
    image-transport
    rclcpp
    rclcpp-components
    sensor-msgs
    std-msgs
    vision-opencv
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
